development:
  sessions:
    default:
      database: web_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: web_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      uri: mongodb://curso:Curs0@ds033841.mongolab.com:33841/heroku_app33368286
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 15
        refresh_interval: 10
  options:
